version: '3.4'

services:
  tega:
    image: tega
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5001:5001
    volumes:
      - /Users/theo/VSCode/tega/config.py:/app/config.py
    depends_on:
      - tega-db

  tega-db:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=tegatoolkit
      - MYSQL_ROOT_PASSWORD=changeme123
      - MYSQL_USER=tega
      - MYSQL_USER_PASSWORD=changeme123