version: '3.4'

services:
  tega:
    container_name: tega
    image: tega
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5001:5001
    environment:
      - SQLALCHEMY_DATABASE_URI=mysql://${MYSQL_USER}:${MYSQL_USER_PASSWORD}@tega-db/${MYSQL_DATABASE}
    volumes:
      - /Users/theo/VSCode/tega/config.py:/app/config.py
    depends_on:
      - tega-db
    restart: unless-stopped

  tega-db:
    container_name: tega-db
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=tegatoolkit
      - MYSQL_ROOT_PASSWORD=changeme123
      - MYSQL_USER=tega
      - MYSQL_PASSWORD=changeme123
    restart: unless-stopped